[project]
name = "odoo-addons-oca-sustainability"
version = "19.0.20260922.0"
dependencies = [
    "odoo-addon-sustainability==19.0.*",
    "odoo-addon-sustainability_purchase==19.0.*",
    "odoo-addon-sustainability_spreadsheet_dashboard==19.0.*",
]
classifiers=[
    "Programming Language :: Python",
    "Framework :: Odoo",
    "Framework :: Odoo :: 19.0",
]
